title: Moruff Raheem Data Analytics Portfolio
logo: Moruff.png
description: A data analyst with 2 years experience working across different sectors, highly skilled in SQL, Excel and Power BI.
#show_downloads: true
#google_analytics:
theme: jekyll-theme-minimal
